### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by franvala** [AntonelliLab/raxmlGUI#82] opened 2019-12-06 18:07 UTC
Autogenerated report:
```json
{
  "message": "Exited with code 1. Check console output for more information.",
  "name": "Error",
  "stack": "Error: Exited with code 1. Check console output for more information.\n    at ChildProcess.<anonymous> (C:/Users/franc/AppData/Local/Temp/1TRvvn3aWQvg0gGFGmxVg2qxlQm/resources/app.asar/build/electron.js:1:11366)"
}
```

Active state:
```json
{
  "command": "raxmlHPC-PTHREADS-SSE3.exe -T 2 -f a -x 344 -p 401 -N 100 -m GTRGAMMA -O -o NG_027602.1_Aleuria_aurantia -n Otidea_Etrechy_LSU_aligned.tre -s \"E:\\aMonMycoseq\\Otidea\\Otidea Etrechy LSU aligned.fas\" -w \"E:\\aMonMycoseq\\Otidea\"",
  "stdout": ""
}
```

---

Process: renderer
raxmlGUI 2.0.0-beta.2
Electron 6.0.2
win32 10.0.17763
Locale: fr

**Comment by jtklein** [comment] 2019-12-07 14:16
Duplicate of #81

**Closed by jtklein** 2019-12-07 14:16 UTC
