### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by yjgcy** [AntonelliLab/raxmlGUI#191] opened 2021-05-28 17:41 UTC
Autogenerated report:
```json
{
  "name": "Error",
  "message": "Exited with code 3. Check console output for more information.",
  "stack": "Error: Exited with code 3. Check console output for more information.\n    at ChildProcess.<anonymous> (C:/Users/Asus/AppData/Local/Programs/raxmlgui/resources/app.asar/build/electron.js:1:21493)"
}
```

Active state:
```json
{
  "command": "raxmlHPC-PTHREADS-SSE3.exe -T 2 -f a -x 823827 -p 823827 -N 100 -m MULTICATX -K GTR -k -O -o OG -n Mariposas_1.tre -s \"F:\\JGC\\Cursos\\Sistematica Filogenetica\\Laboratorio\\Raxml\\Mariposas.phy\" -w \"F:\\JGC\\Cursos\\Sistematica Filogenetica\\Laboratorio\\Raxml\"",
  "stdout": "[12430 more characters]... Bootstraps 2.128469 seconds\r\nAverage Time per Rapid Bootstrap 0.021285 seconds\r\n\r\nStarting ML Search ...\r\n\r\n-37.8622081209648940000000000000000000000000 -37.8199110705779020000000000000000000000000\r\n"
}
```

---

Process: renderer
raxmlGUI 2.0.5
Electron 12.0.7
win32 10.0.19042
Locale: es

**Comment by danieledler** [comment] 2021-05-31 19:07
Hi, and thanks for reporting the issue!

I'm not sure yet what the problem is, raxml started but exited with code 3 after the bootstrap part, just after starting ML search.

I'm thinking of two possible issues:
1. raxml tries to allocate memory but fails
2. raxml tries to write output to a path that it can't access

If the first, it should work with a smaller dataset, what is the size of your data? Can you try with one of the [example files from our homepage](https://antonellilab.github.io/raxmlGUI/)?

If the second, can you try selecting output folder on the C drive?

Can you also try to run after selecting another raxml binary, one without PTHREADS?

If it doesn't help, has it worked before? If so, what differ now?

**Comment by yjgcy** [comment] 2021-06-01 00:15
Dear Daniel
The file that I was using had the FASTA format, curiously the first time I
ran it in raxmlGUI, the program ran ok, however, the second time that I
tried to run it again, the program didn't work. That's when I sent the
notification of the problem. Sorry.
Now, the file has the Phyllip format and it works ok. Thank you for your
help
Regards, Javier
_____________________________
Dr. Javier García Cruz
Jefe del Área de Botánica Estructural y Sistemática Vegetal
Departamento de Biología, UAM Iztapalapa

**Comment by danieledler** [comment] 2021-06-01 07:47
Ok, glad it works now! I will close this issue now, but if you can share your fasta file that created the issue, we can try to see if we can reproduce the problem and hopefully prevent similar issues in the future.

Thanks!

**Closed by danieledler** 2021-06-01 07:47 UTC
