### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rudrakumarpandey888** [AntonelliLab/raxmlGUI#202] opened 2021-08-20 13:34 UTC
Autogenerated report:
```json
{
  "name": "Error",
  "message": "Error parsing file D:\\SARS-COV2\\Latest\\zzz\\ALL ALPHA.fasta: Sequence 'hCoV-19/India/MH-NIV-VOC-389/2021' have different length (29876) than previous taxons (29788).",
  "stack": "Error: Error parsing file D:/SARS-COV2/Latest/zzz/ALL ALPHA.fasta: Sequence 'hCoV-19/India/MH-NIV-VOC-389/2021' have different length (29876) than previous taxons (29788).\n    at fastaParser_parse$0 (C:/Users/RUDRA/AppData/Local/Programs/raxmlgui/resources/app.asar/build/electron.js:1:16712)\n    at Interface.<anonymous> (C:/Users/RUDRA/AppData/Local/Programs/raxmlgui/resources/app.asar/build/electron.js:1:17290)"
}
```

Active state:
```json
{
  "command": "raxmlHPC-PTHREADS-SSE3.exe -T 2 -f a -x 877822 -p 877822 -N 100 -m GTRGAMMA -O -n ALL_ALPHA.tre -s \"D:\\SARS-COV2\\Latest\\zzz\\RAxML_ALL_ALPHA_concat.txt\" -w \"D:\\SARS-COV2\\Latest\\zzz\"",
  "stdout": ""
}
```

---

Process: renderer
raxmlGUI 2.0.5
Electron 12.0.7
win32 10.0.19043
Locale: en-US

**Comment by jtklein** [comment] 2021-09-07 15:52
Thank you for the error report.
I am closing this, because it is a duplicate of #192.

**Closed by jtklein** 2021-09-07 15:52 UTC
