### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by JonathanChou** [AntonelliLab/raxmlGUI#197] opened 2021-07-20 08:30 UTC
Autogenerated report:
```json
{
  "name": "Error",
  "message": "Error parsing file /Users/jonathanchou/Desktop/COI_消費帶魚.fasta: Sequence '102_Tj Tj' have different length (579) than previous taxons (580).",
  "stack": "Error: Error parsing file /Users/jonathanchou/Desktop/COI_消費帶魚.fasta: Sequence '102_Tj Tj' have different length (579) than previous taxons (580).\n    at fastaParser_parse$0 (/Applications/raxmlGUI.app/Contents/Resources/app.asar/build/electron.js:1:16712)\n    at Interface.<anonymous> (/Applications/raxmlGUI.app/Contents/Resources/app.asar/build/electron.js:1:17290)"
}
```

Active state:
```json
{
  "command": "raxml-ng --all --msa /Users/jonathanchou/Desktop/Paper Charts/RAxML_COI_消費帶魚_concat.txt --model  --prefix /Users/jonathanchou/Desktop/Paper Charts/COI_消費帶魚 --seed 748210 --bs-metric tbe --tree rand{1} --bs-trees 100",
  "stdout": ""
}
```

---

Process: renderer
raxmlGUI 2.0.5
Electron 12.0.7
darwin 19.6.0
Locale: en-US

**Comment by jtklein** [comment] 2021-09-07 16:11
Thank you for the error report.
I am closing this, because it is a duplicate of #192

**Closed by jtklein** 2021-09-07 16:11 UTC
