### ISSUE TITLE
Possible duplicate Error: Exited with code 3.

### ISSUE THREAD

**Issue by hym011** [AntonelliLab/raxmlGUI#263] opened 2022-05-19 04:04 UTC
Autogenerated report:
```json
{
  "name": "Error",
  "message": "Exited with code 3. Check console output for more information.",
  "stack": "Error: Exited with code 3. Check console output for more information.\n    at ChildProcess.<anonymous> (C:/Users/ymheo/AppData/Local/Programs/raxmlgui/resources/app.asar/build/electron.js:1:19668)"
}
```

Active state:
```json
{
  "command": "raxmlHPC-PTHREADS-SSE3.exe -T 6 -f a -x 11349 -p 11349 -N 100 -m GTRGAMMAX --JC69 -k -O -n material_final_modified_4.tre -s \"C:\\Users\\ymheo\\Downloads\\material_final_modified.fas\" -w \"C:\\Users\\ymheo\\Downloads\"",
  "stdout": "[26587 more characters]...HREADS-SSE3.exe -T 6 -f a -x 11349 -p 11349 -N 100 -m GTRGAMMAX --JC69 -k -O -n material_final_modified_3.tre -s C:\\Users\\ymheo\\Downloads\\material_final_modified.fas -w C:\\Users\\ymheo\\Downloads \r\n\r\n\r\n"
}
```

---

Process: renderer
raxmlGUI 2.0.8
Electron 13.6.2
win32 10.0.22000
Locale: ko

**Comment by jtklein** [comment] 2022-06-22 10:54
Duplicate of #249

**Closed by jtklein** 2022-06-22 10:54 UTC
